### PR TITLE
I have a template... not complete, of course.

### PR DESCRIPTION
**Pull request by ghost**
You will need to improve on this, of course.

### CODE REVIEW

**Comment by benburrill** [comment]
Why don't you take a look at [this](http://jinja.pocoo.org/docs/dev/templates/).  It should give you some idea as to how to use jinja2 templates.  If you want to experiment with them, you can run view-front-end.py to see the rendered template.

**Comment by ghost** [comment]
I just read... part of it. Wow. It reminds be somewhat of PHP.

Of course, we need a way to push the _final_ HTML document to the KA webpage, not the Jinja version.
Does  J i n j a  ignore `<script>` tags?

**Comment by benburrill** [comment]
1. Yeah, it's a lot of stuff.  We don't really need most of it, I'm mostly using jinja2 for very simple stuff.  You might want to take a look at [the other game's templates](https://github.com/Potato42/kacpaw-game/tree/master/templates) to get a sense of how I was using them.
2. That's easy.  You just need to use the `render()` method of a template.  We already have that working both in the other game and in view-front-end.py
3. No.  Although the intended purpose of jinja2 is html, it's really just a fancy formatter.  You can use jinja2 inside script tags.  In fact, we will (and already [do](https://github.com/Potato42/kacpaw-game/blob/master/templates/program.html#L18) in the old project) use that to inject JSON data into the JS.  Luckily, unlike something like `str.format`, jinja2's syntax doesn't really conflict with JS's.

**Comment by ghost** [comment]
Cool. So I guess our G2/3A game won't need user "accounts", but more complicated games like a secret spy mission would.

Another option is to recreate poll chess and use the bot to track moves... although parsing moves is complicated

**Pull request merged**
